### Récupérer tous les spaces
GET http://localhost:8080/api/spaces
Accept: application/json

### Repurer space avec ID
GET http://localhost:8080/api/spaces/0e0ad931-c437-4798-9092-de9b837e1504

### Ajouter un space
POST http://localhost:8080/api/spaces
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiU3lzdGVtIiwicm9sZSI6IkFETUlOIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwidXNlcklkIjoiMzM4NjQ3MjctYjdhNi00NmJhLWExMDAtNzY3NWNlNjc5NjE3Iiwic3ViIjoiYWRtaW5AZW5zYW0tY2FzYS5tYSIsImlhdCI6MTc3NTY5MDQyNCwiZXhwIjoxNzc1NjkxMzI0fQ.XQ1OADIKpjlMxCXKlprBAeuiH3jNhkcv_pIS4jVQ_Gs

{
  "name" : "Back-end",
  "color": "red",
  "workspaceid": "e3352baf-ae03-470e-a32d-e823c7857887",
  "isPrivate": false
}

### Modifier un Space
PUT http://localhost:8080/api/spaces/0e0ad931-c437-4798-9092-de9b837e1504
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiU3lzdGVtIiwicm9sZSI6IkFETUlOIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwidXNlcklkIjoiMzM4NjQ3MjctYjdhNi00NmJhLWExMDAtNzY3NWNlNjc5NjE3Iiwic3ViIjoiYWRtaW5AZW5zYW0tY2FzYS5tYSIsImlhdCI6MTc3NTY5MjA1MywiZXhwIjoxNzc1NjkyOTUzfQ.4sNPB4YSWjCM6Sd3VAHQjEmonHJnOO2jXAVXUFdJBZg

{
  "name" : "Back-end",
  "color": "blue",
  "workspaceid": "e3352baf-ae03-470e-a32d-e823c7857887",
  "isPrivate": false
}

### Delete space
DELETE http://localhost:8080/api/spaces/0e0ad931-c437-4798-9092-de9b837e1504