### Récupérer tous les workspaces
GET http://localhost:8080/api/workspaces
Accept: application/json

### Créer  un Workspace
POST http://localhost:8080/api/workspaces
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiU3lzdGVtIiwicm9sZSI6IkFETUlOIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwidXNlcklkIjoiN2ZlYmFkY2QtMDRlZi00MDYwLTg0MDgtY2YwYTU1NTViY2JkIiwic3ViIjoiYWRtaW5AZW5zYW0tY2FzYS5tYSIsImlhdCI6MTc3NTk0MjAxOCwiZXhwIjoxNzc1OTQyOTE4fQ.Aou3IuPfAcoJ03QEU6Wxvle4MWNFLbu_lvaJMU1As0w


{
  "name": "Projet IT",
  "slug": "IT-2026"
}

### Modifier un Workspace
PUT http://localhost:8080/api/workspaces/7a938497-66bd-4966-9285-e7112b6eb657
Content-Type: application/json
Authorization: Bearer "acess token"

{
  "name": "Projet Electrique",
  "slug": "Electrique-2026"
}

### Delete workspace
DELETE http://localhost:8080/api/workspaces/5332c8f9-3af2-4fa4-8ae3-488a783eb842

### Get All workspaces By user
GET http://localhost:8080/api/workspaces
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJmaXJzdE5hbWUiOiJBZG1pbiIsImxhc3ROYW1lIjoiU3lzdGVtIiwicm9sZSI6IkFETUlOIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwidXNlcklkIjoiMzM4NjQ3MjctYjdhNi00NmJhLWExMDAtNzY3NWNlNjc5NjE3Iiwic3ViIjoiYWRtaW5AZW5zYW0tY2FzYS5tYSIsImlhdCI6MTc3NTc3ODMwNiwiZXhwIjoxNzc1Nzc5MjA2fQ.mSjKojRf_PNEarudhn2bZrPWWFzsuCb24tllTy9xDCU

